name: Insignia Demo 1
 
on: [push]
 
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            print (" This comes from Python")
        shell: python
  helloworld-2:
     runs-on: ubuntu-latest
     needs: helloworld
     steps:
       - run: echo "Step 1 completed"
       - run: echo "Step 2 completed"
